# Generated by Django 4.2.5 on 2025-07-10 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_feedback_is_escalated_feedback_response_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
